Work around a bug in Octave 4.0.x.
- Bug causes the following error ...
	error: warning: unable to find default warning state!
... after calling warning(S) to restore full warning state.